import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

// async function loader() {

//   const path = "/api/landing-page?=populate=*";
//   const baseUrl = "http://localhost:1337";

//   const url = new URL(path, baseUrl);
//   const response= await fetch(url.href);
//   const data = await response.json();
//   console.log(data)

// }



export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const data = await loader();
  // console.log(data)

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>

        
        {/* <div>Hello World</div> */}
        {children}


      </body>
    </html>
  );
}
