import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/layout/TopNavbar";
import SubscribeSection from "@/components/layout/SubscribeSection";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

// async function loader() {

//   const path = "/api/landing-page?=populate=*";
//   const baseUrl = "http://localhost:1337";

//   const url = new URL(path, baseUrl);
//   const response= await fetch(url.href);
//   const data = await response.json();
//   console.log(data)

// }



export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const data = await loader();
  // console.log(data)

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body>
        <div className="sticky top-0 z-50">
          <TopNavbar />
          <Navbar />
        </div>
        {children}
        <div>
          <SubscribeSection />
          <Footer />
        </div>
      </body>
    </html>
  );
}
