import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import SubscribeSection from "@/components/layout/SubscribeSection";
import TopNavbar from "@/components/layout/TopNavbar";
import { getLandingPageData } from "@/lib/StrapiLandingPage";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};



  export default async function HomeLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    let navbarData = null;

    let footerData = null;
    
    try {
      const strapiData = await getLandingPageData();

      const headerData = strapiData.data.header[0];
      if (headerData) {
        navbarData = {
          phoneNumber: headerData.phoneNumber,
          email: headerData.email,
          socialLinks: headerData.socialLinks,
        };
      }



      const footerSection = strapiData.data.footer[0];

      if(footerSection){
        footerData= {
          id: footerSection.id,
          // newsLetterHeading: footerSection.newsLetterHeading,
          // newsLetterDescription: footerSection.newsLetterDescription,
          // footerCompanyDescription: footerSection.footerCompanyDescription,
          // newsLetterImage: footerSection.newsLetterImage,
          
          // ctaSubscribeLink: footerSection.ctaSubscribeLink,
          // ctaContactLink: footerSection.ctaContactLink,

          socialLinks: footerSection.socialLinks.map((link:any)=>({
            id: link.id,
            text: link.text,
            href: link.href,
            isExternal: link.isExternal
          })),

          contactUs:{
            id: footerSection.contactUs.id,
            address: footerSection.contactUs.address,
            phoneNumber: footerSection.contactUs.phoneNumber,
            email: footerSection.contactUs.email,
            websiteLink: footerSection.contactUs.websiteLink,
            heading: footerSection.contactUs.heading

          },

          openingHours: {
            id: footerSection.openingHours.id,
            heading: footerSection.openingHours.heading,
            dayRange1: footerSection.openingHours.dayRange1,
            dayRange2: footerSection.openingHours.dayRange2

          },

          quickLink: {
            id: footerSection.quickLink.id,
            heading: footerSection.quickLink.heading,
            links: footerSection.quickLink.links.map((link: any)=>({
              id: link.id,
              text: link.text,
              href: link.href,
              isExternal: link.isExternal
            }))
          }
        }
      }

    } catch (error) {
      console.error('Failed to fetch landing page data:', error);
      
    }

    return (
      <html lang="en">
        <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        </head>
        <body>
          <div className="sticky top-0 z-50">
            <TopNavbar navbarData={navbarData ?? undefined} />
            <Navbar />
          </div>
          {children}
          <div>
            <SubscribeSection />
            <Footer footerData={footerData  } />
          </div>
        </body>
      </html>
    );
  }
