import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import SubscribeSection from "@/components/layout/SubscribeSection";
import TopNavbar from "@/components/layout/TopNavbar";
import { getLandingPageData } from "@/lib/StrapiLandingPage";
import type { Metadata } from "next";
import "./globals.css";



  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",

  };

  export default async function HomeLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    let navbarData = null;
    try {
      const strapiData = await getLandingPageData();

      const headerData = strapiData.data.header[0];
      if (headerData) {
        navbarData = {
          phoneNumber: headerData.phoneNumber,
          email: headerData.email,
          socialLinks: headerData.socialLinks,
        };
      }
    } catch (error) {
      console.error('Failed to fetch landing page data:', error);
      
    }

    

    return (
      <html lang="en">
        <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        </head>
        <body>
          <div className="sticky top-0 z-50">
            <TopNavbar navbarData={navbarData ?? undefined} />
            <Navbar />
          </div>
          {children}
          <div>
            <SubscribeSection />
            <Footer />
          </div>
        </body>
      </html>
    );
  }
